# Change these first
owner: Jerit3787 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Main Website
    url: https://www.danishplace.tech
  - name: API
    url: https://www.danishsite.ml
  - name: Projects Website
    url: https://projects.danishplace.tech
  - name: Links Website
    url: https://links.danishplace.tech
  - name: Social Links Website
    url: https://personal.danishplace.tech
  - name: Project Stutastic
    url: https://stutastic.danishplace.tech
  - name: Stutastic Planner
    url: https://planner.danishplace.tech
  - name: Channel Buku Teks Website
    url: https://www.channelbukuteks.tk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.danishplace.tech
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Jerit3787's Project Status Page"
  theme: dark
  introTitle: "This page gives you real-time data of my current projects website status."
  introMessage: "This website is still under testing! Data shown here may or not as accurate for now!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Jerit3787

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
