# Change these first
owner: Jerit3787 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Main Website
    url: https://www.danplace.tech
  - name: API Server
    url: https://api.danplace.tech/v3/status/check
  - name: CDN Website
    url: https://cdn.stutastic.danplace.tech
  - name: Projects Website
    url: https://projects.danplace.tech
  - name: Links Website
    url: https://links.danplace.tech
  - name: Social Links Website
    url: https://personal.danplace.tech
  - name: Project Stutastic
    url: https://stutastic.danplace.tech
  - name: Tracking Website
    url: https://tracking.danplace.tech
  - name: Stutastic Planner
    url: https://planner.danplace.tech
  - name: Channel Buku Teks Website
    url: https://bukuteks.github.io
  - name: Status Website
    url: https://status.danplace.tech

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.danplace.tech
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: "Jerit3787's Project Status Page"
  theme: dark
  introTitle: "This page gives you real-time data of my current projects website status."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/Jerit3787

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
